on: push
jobs:
  i686:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get update && sudo apt-get install -y git curl build-essential nasm texinfo libgmp-dev libmpfr-dev libmpc-dev lzip e2tools grub2-common grub-pc-bin mtools xorriso parted qemu-system-x86 tofrodos sysvbanner
    - run: make cdrom.iso
